[package]
name = "eternal-web"
description = "WebAssembly bindings for Eternal Jukebox"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
eternal-core = { path = "../eternal-core" }
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
