[package]
name = "eternal-core"
description = "Audio analysis and branching playback engine for Eternal Jukebox"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rand.workspace = true
realfft.workspace = true
serde.workspace = true
symphonia.workspace = true
symphonia-adapter-libopus.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true

